import { Journey, Evidence, Milestone, ProofStory, AIInsights } from '../types';

export const DEMO_EVIDENCE: Evidence[] = [
  {
    id: 'demo-ev-1',
    journey_id: 'demo-journey-art',
    day_number: 1,
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB4ayyYzxRlCjya9DMwSWDGW59X406G-4EN6GrMn7nGxblLfInFIL1O2eybN-U2NLgVgV0y3-Cccew_phgQjVBNC2F1PyIpnTjLwCbjuQlTwYXDNsGKI-Tv_n-G5GuCALJJDjtSeR5s3WobN6C-Kxc6r2Em83S8ClpGeLBprThY7ptOFoGuu9cYPK1UipMqGNSntW9ovIQXCaM-uyIa7vFyD-qpXR_aCeCccQNWzoJAMDUV-wLZAnowQA',
    reflection: 'First session with digital stylus. Hesitant strokes, sketching basic spherical wireframes and contour shapes on craft paper backdrop.',
    prompt_spark: 'What changed?',
    metrics_tag: 'D·01 · RAW SKETCH',
    captured_at: '2024-08-01T20:30:00Z',
    order_index: 1,
  },
  {
    id: 'demo-ev-7',
    journey_id: 'demo-journey-art',
    day_number: 7,
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrstUIWjTh0yRm2Mki-BGHgijMOZyEl4ruAWnB2sWIJBlJg86hXKg4j1hbtnc4l_qYsfzf-AD8a6yMMG5NWmCxqVG_E6lMiUo2puvheFUAaEDrcTwe-X2b4kmeKvhM0YSCwDv_gQqLdrNmerVlXGgcouplaUj8ubbr5o_bzdn_ZiogJxImWu1jIO94e1FyOA3KHOwbilqAGBcTEI66o7qPfDrJB0aoyby98Baq1SDw6PHzXSgsmBN5uA',
    reflection: 'Transitioned to basic shading. Nightly 45-minute tablet ritual without breaking cadence. Discovered core shadows and ambient occlusion.',
    prompt_spark: 'What did you learn?',
    metrics_tag: 'D·07 · TONAL STUDY',
    captured_at: '2024-08-07T21:15:00Z',
    order_index: 2,
  },
  {
    id: 'demo-ev-15',
    journey_id: 'demo-journey-art',
    day_number: 15,
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDi9yi1t-j14-mBcX182YP04wnFFCNqMrPEQSNWZhZ0ph8kLRuqnF3Heza39meSKTe0r5_k99Lx-u_pOlDFaSuTmi0PeY1N97d54B2B_I3AWZaReo3SE8Gzl_oe72tLwwwF9i4k6yVusscXFk9FItYP_tELZ9fM5mA94XZVSIvqmOw-iy1-A-qMgTUYTXXgV4iEcgmWUPSPXcZSSn-YvKj0rlTu3L-4tmuNMo43-SytdRRjaPkXcbuQSA',
    reflection: 'Started experimenting with volumetric lighting and atmospheric rim light. Found that darkening the ambient background made the focal lantern pop.',
    prompt_spark: 'What was difficult?',
    metrics_tag: 'D·15 · VOLUMETRIC',
    captured_at: '2024-08-15T23:42:00Z',
    order_index: 3,
  },
  {
    id: 'demo-ev-23',
    journey_id: 'demo-journey-art',
    day_number: 23,
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBahxMq3MKix_UvTKHXu7K2R_tdQnxfNl6ENpLFMRVkyKerjQ4Ft8j4mdE2CfIROwZ7Yrt-QeJdxvWZIZ9GJJOt1LiV-p67R2LwVUjniA1WbF6tAiLstWJFG5xRZJr_w7hxOTk7olzpxdf5mzgoD8zTc3D9lCh-DX7P8mBkFYGmxGgMekdfVN09FoW2CH9LTFecgm5TBHCTw8TkItZ5YIYg4LFEtMhNCInN7o7qaG14iXnQpB7nvFiCnQ',
    reflection: 'Dome studies and architectural framework. Practicing sub-surface light scattering and reflective water planes beneath glass vaults.',
    prompt_spark: 'What made you proud?',
    metrics_tag: 'D·23 · ARCHITECTURE',
    captured_at: '2024-08-23T22:10:00Z',
    order_index: 4,
  },
  {
    id: 'demo-ev-30',
    journey_id: 'demo-journey-art',
    day_number: 30,
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDxzsJbZ3fyRnQzhFJJszTK49JoJ7iqoQX5Mtqx2jUr3JfM7INbF_u8WmmuD_pX6XNOBPCsxCLwPNKGCnXWchcbaPbJq87acGStaVyK4WSUhRAK4ZWd1GA_501cKMuJM6a7uWIJrzJNHCx6aa7CRYdxI67c6vXqXaRnoLFnYoP56iihDd49NvnnzpP8bxuYn0plRNT-6VPu4LzhDokeM2_QYjI_VovVf2zhCNSMF_x4KzKXpG_G4Dnrzw',
    reflection: 'Finished sanctuary concept opus. Bioluminescent glass dome surrounded by glowing teal flora and dusk atmosphere. A complete synthesis of form, light, and depth.',
    prompt_spark: 'What changed?',
    metrics_tag: 'D·30 · MASTERPIECE',
    captured_at: '2024-08-30T23:55:00Z',
    order_index: 5,
  },
];

export const DEMO_MILESTONES: Milestone[] = [
  {
    id: 'demo-ms-1',
    journey_id: 'demo-journey-art',
    day_number: 1,
    title: 'First Evidence Captured',
    description: '"Rough pencil geometry" — Confronted the digital stylus friction for the very first time.',
    reached_at: '2024-08-01T20:30:00Z',
    is_completed: true,
  },
  {
    id: 'demo-ms-2',
    journey_id: 'demo-journey-art',
    day_number: 7,
    title: '7-Day Consistency',
    description: '"Transitioned to basic shading" — Established a nightly 45-minute tablet ritual without breaking cadence.',
    reached_at: '2024-08-07T21:15:00Z',
    is_completed: true,
  },
  {
    id: 'demo-ms-3',
    journey_id: 'demo-journey-art',
    day_number: 15,
    title: 'Lighting Breakthrough',
    description: '"Atmospheric rim lighting" — Discovered how specular reflections reveal curvature and environmental depth.',
    reached_at: '2024-08-15T23:42:00Z',
    is_completed: true,
  },
  {
    id: 'demo-ms-4',
    journey_id: 'demo-journey-art',
    day_number: 30,
    title: '30-Day Series Completion',
    description: '"Finished sanctuary concept" — Culmination of multi-layer illumination, glass reflection, and botanical organic modeling.',
    reached_at: '2024-08-30T23:55:00Z',
    is_completed: true,
  },
];

export const DEMO_JOURNEYS: Journey[] = [
  {
    id: 'demo-journey-art',
    user_id: 'demo-user-guest',
    title: 'Learning Digital Art',
    category: 'Art',
    duration_days: 30,
    description: 'A 30-day dedicated sprint exploring form, lighting, and worldbuilding in Procreate.',
    is_active: true,
    created_at: '2024-08-01T00:00:00Z',
    current_day: 30,
    evidence_count: 5,
    milestone_count: 4,
    latest_evidence: DEMO_EVIDENCE[4],
    evidence: DEMO_EVIDENCE,
    milestones: DEMO_MILESTONES,
  },
  {
    id: 'demo-journey-guitar',
    user_id: 'demo-user-guest',
    title: 'Learning Guitar',
    category: 'Music',
    duration_days: 30,
    description: 'Fingerstyle intro and Canon in D progression.',
    is_active: true,
    created_at: '2024-09-12T00:00:00Z',
    current_day: 18,
    evidence_count: 9,
    milestone_count: 2,
    latest_evidence: {
      id: 'demo-ev-guitar-1',
      journey_id: 'demo-journey-guitar',
      day_number: 18,
      image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDbXU_Zg9a2XLBgkDVOx2zkyBKrGIwrcUI7F0-sgXHqn6Hm_T-ZOfg1-mOQj2qbTKEd_lOdalKfWRGYfzI6sQ9N_7clUduNuhmyyxVtmwhWpn2jpFWHoyPXEIwMp5QFIE9HAD2P-lQ0JGWGlLYIPac033r0tWyK-MQfJqPNXxM_NBu9XOfekUl2xgK6_R3BH3dcvAF2kddaWSd_3uTCfAnw72ZD5v2NrQhQiRGzSqVnikLafDXs0pY6ng',
      reflection: 'Canon in D bars 1-8 fingerstyle transition. Switching to F chord without audible pause.',
      metrics_tag: 'DAY 18 · AUDIO LOG',
      captured_at: '2024-09-30T19:00:00Z',
      order_index: 9,
    },
    evidence: [],
    milestones: [],
  },
];

export const DEMO_AI_INSIGHTS: AIInsights = {
  ai_used: true,
  model_name: 'Qwen/Qwen3-4B-Instruct-2507',
  journey_title: 'Learning Digital Art',
  grounded_entries_count: 5,
  key_shift: 'Your reflections shifted around Day 15 from tentative monochrome outlines to active experimentation with specular rim lighting, leading directly to the volumetric depth in Day 30.',
  growth_trajectory: 'Gesture & Form → Volumetric Light → Worldbuilding',
  observations: [
    'Day 1 captured foundational sphere outlines with hesitant pressure curves.',
    'Day 15 was the turning point: you darkened background values to emphasize glowing lantern warmth.',
    'Day 30 reached complete scene harmony with architectural glass reflections and bioluminescent foliage.',
  ],
  sentiment_summary: 'Shift from early uncertainty to assertive artistic confidence across 30 days of documented proof.',
  generated_at: '2024-08-31T00:00:00Z',
};

export const DEMO_PROOF_STORY: ProofStory = {
  id: 'demo-story-1',
  journey_id: 'demo-journey-art',
  title: 'Learning Digital Art Retrospective',
  total_days: 30,
  hours_invested: 42.5,
  captures_count: 5,
  mastery_delta: '+84%',
  chapters: [
    {
      day_number: 1,
      title: 'The Starting Point',
      image_url: DEMO_EVIDENCE[0].image_url,
      badge_label: 'RAW SKETCH',
      narrative: 'Hesitant pencil strokes. Establishing basic geometric form and tentative hatching.',
    },
    {
      day_number: 7,
      title: 'First Realization',
      image_url: DEMO_EVIDENCE[1].image_url,
      badge_label: 'TONAL STUDY',
      narrative: 'Discovered value contrast, ambient occlusion, and confident edge control.',
    },
    {
      day_number: 15,
      title: 'The Lighting Pivot',
      image_url: DEMO_EVIDENCE[2].image_url,
      badge_label: 'VOLUMETRIC',
      narrative: 'First experiment with vibrant volumetric warmth, mist diffusion, and specular reflections.',
    },
    {
      day_number: 30,
      title: 'The Breakthrough',
      image_url: DEMO_EVIDENCE[4].image_url,
      badge_label: 'MASTERPIECE',
      narrative: 'Complete scene orchestration, complex subsurface light interaction, and cinematic depth.',
    },
  ],
  culmination_quote: 'From a tentative 5-minute sphere sketch to a living bioluminescent world. Look how far you have come.',
  created_at: '2024-08-31T01:00:00Z',
};
